graph LR
    subgraph "Real-time Events"
        PC[Post Created]
        CC[Comment Created]
        PL[Post Liked]
        NC[Notification Created]
    end
    
    subgraph "Supabase Realtime"
        CH[Channels]
        SUB[Subscriptions]
    end
    
    subgraph "Client Components"
        AF[Activity Feed]
        PM[Post Modal]
        NB[Notification Bell]
    end
    
    PC --> CH
    CC --> CH
    PL --> CH
    NC --> CH
    
    CH --> SUB
    
    SUB --> AF
    SUB --> PM
    SUB --> NB
    